# -*- coding: utf-8 -*-
"""adc_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8dHZJh53hzLj35bRhRJWhI-7xJSbuN6
"""

import numpy as np
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt

# ADC = X,  weights = Y
adc_readings = np.array([2.5, 7.5,  17.5, 22.5,   51.5,  88.91, 205,  419, 473.8])  #  ADC readings
real_weights = np.array([20.1, 48.8, 139.7, 205.8, 499.5, 881.3, 1992.3, 3989.7, 4489.2])  # real weigh

degree = 1

# Fit a polynomial
coefficients = np.polyfit(adc_readings, real_weights, degree)
print("Coefficients:", coefficients)

# Create an interpolation function using scipy's interp1d
interpolation_function = interp1d(adc_readings, real_weights, kind='linear', fill_value='extrapolate')

# Replace with new ADC readings
new_adc_readings = np.array([299, 300, 310 , 348, 382, 800])
estimated_weights = interpolation_function(new_adc_readings)

# Plot the original data points and the interpolated function
plt.scatter(adc_readings, real_weights, label='Pontos Lidos')
plt.plot(new_adc_readings, estimated_weights, label='Funcao Interpolada', linestyle='dashed')
plt.xlabel('ADC')
plt.ylabel('Balança')
plt.legend()
plt.grid()
plt.show()